name: Create Release

on: 
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.15.1
        uses: actions/setup-node@v3
        with:
          node-version: "20.15.1"
          cache: "npm"
      - run: npm ci
      - run: npm test

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.15.1
        uses: actions/setup-node@v3
        with:
          node-version: "20.15.1"
          cache: "npm"
      - run: npm ci
      - run: npm run lint
    
  createRelease: 
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create release branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'releases/${{ github.run_number }}'
          sha: ${{ github.sha }}
           
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build docker images
        run: |
          docker build -t cr.yandex/crp4eluf48bv0u242o2t/app:${{ github.run_number }} .
          docker tag cr.yandex/crp4eluf48bv0u242o2t/app:${{ github.run_number }} cr.yandex/crp4eluf48bv0u242o2t/app:latest
      
      - name: Push docker images
        run: |
          docker push cr.yandex/crp4eluf48bv0u242o2t/app:${{ github.run_number }}
          docker push cr.yandex/crp4eluf48bv0u242o2t/app:latest
