name: Создать фикс

on:
  workflow_dispatch:
    inputs:
      release_version:
        required: true
        description: Укажите версию релиза для фикса
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.15.1
        uses: actions/setup-node@v3
        with:
          node-version: "20.15.1"
          cache: "npm"
      - run: npm ci
      - run: npm test

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.15.1
        uses: actions/setup-node@v3
        with:
          node-version: "20.15.1"
          cache: "npm"
      - run: npm ci
      - run: npm run lint
  createFix:
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - name: Проверка репозитория
        uses: actions/checkout@v4

      - name: Авторизация в GitHub
        run: |
          git config --global user.email "yaroslav.patrikeev@gmail.com"
          git config --global user.name "Yaroslav"

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Авторизация в Docker
        run: |
          docker login \
            --username oauth \
            --password ${{ secrets.PASSWORD }} \
            cr.yandex

      - name: Создание основного образа и push
        run: |
          docker build -t cr.yandex/crp4eluf48bv0u242o2t/app:${{ github.event.inputs.release_version }}_fix${{ github.run_number }} .
          docker push cr.yandex/crp4eluf48bv0u242o2t/app:${{ github.event.inputs.release_version }}_fix${{ github.run_number }}

      - name: Добавление тега _latest и push
        run: |
          docker tag cr.yandex/crp4eluf48bv0u242o2t/app:${{ github.event.inputs.release_version }}_fix${{ github.run_number }} cr.yandex/crp4eluf48bv0u242o2t/app:${{ github.event.inputs.release_version }}_latest
          docker push cr.yandex/crp4eluf48bv0u242o2t/app:${{ github.event.inputs.release_version }}_latest

      - name: Добавление тега фикса
        run: |
          git tag -a v${{ github.event.inputs.release_version }}_fix${{ github.run_number }} -m 'Фикс релиза ${{ github.run_number }}'
          git push origin --tags

      - name: Комментарий к Issue
        run: |
          touch $ISSUE
          echo "## Отчет о фиксе релиза" >> $ISSUE
          echo "- Дата: $(date)" >> $ISSUE
          echo "- Автор фикса: ${{ github.triggering_actor }}" >> $ISSUE
          echo "- Список коммитов:" >> $ISSUE
          git log --pretty=oneline >> $ISSUE
          echo "- Ссылка на docker-образ: cr.yandex/crp4eluf48bv0u242o2t/app:${{ github.run_number }}" >> $ISSUE
          number=$(gh issue list --search "label:релиз ${{ github.event.inputs.release_version }}")
          gh issue comment "$number" --body-file "$ISSUE"
          rm $ISSUE
        env:
          ISSUE: issue.txt
          GH_TOKEN: ${{ github.token }}
