name: Create Release

on: 
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.15.1
        uses: actions/setup-node@v3
        with:
          node-version: "20.15.1"
          cache: "npm"
      - run: npm ci
      - run: npm test

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.15.1
        uses: actions/setup-node@v3
        with:
          node-version: "20.15.1"
          cache: "npm"
      - run: npm ci
      - run: npm run lint
    
  createRelease: 
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create release branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'releases/${{ github.run_number }}'
          sha: ${{ github.sha }}
           
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authorization
        run: |
          docker login \
            --username oauth \
            --password y0_AgAAAABbQqE7AATuwQAAAAEKt6qvAABZVpjhhzVNYrKGvYEX8yP573B8IA \
            cr.yandex
      
      - name: Build/Push Main
        run: |
           docker build -t cr.yandex/crp4eluf48bv0u242o2t/app:${{ github.run_number }} .
           docker push cr.yandex/crp4eluf48bv0u242o2t/app:${{ github.run_number }}
        
      - name: Tag/Push Latest
        run: |
           docker tag cr.yandex/crp4eluf48bv0u242o2t/app:${{ github.run_number }} cr.yandex/crp4eluf48bv0u242o2t/app:${{ github.run_number }}_latest
           docker push cr.yandex/crp4eluf48bv0u242o2t/app:${{ github.run_number }}_latest
      - name: Create Issue
        run: |
          touch $ISSUE
          echo "## Отчет о релизе" >> $ISSUE
          echo "- Дата: $(date)" >> $ISSUE
          echo "- Автор релиза: ${{ github.triggering_actor }}" >> $ISSUE
          echo "- Номер версии: ${{ github.run_number }}" >> $ISSUE
          echo "- Список коммитов:" >> $ISSUE
          git log --pretty=oneline >> $ISSUE
          echo "- Ссылка на docker-образ: cr.yandex/crp4eluf48bv0u242o2t/app:${{ github.run_number }}" >> $ISSUE
          gh issue create --title "Создан новый релиз [${{ github.run_number }}]" --body-file $ISSUE
          rm $ISSUE
        env:
          ISSUE: issue.txt
          GH_TOKEN: ${{ github.token }}
      - name: CHANGELOG
        run: |
          touch $TEMP
          cat $CHANGELOG > $TEMP
          touch $CHANGELOG
          echo "## ${{ github.run_number }}" >> $CHANGELOG
          git log --pretty=oneline >> $CHANGELOG
          cat $TEMP >> $CHANGELOG
          rm $TEMP
          git config --global user.email "yaroslav.patrikeev@gmail.com"
          git config --global user.name "Yaroslav"
          git add CHANGELOG.md
          git commit -m "Обновление changelog в связи с релизом ${{ github.run_number }}"
          git push origin releases/${{ github.run_number }}
        env:
          CHANGELOG: CHANGELOG.md
          TEMP: CHANGELOG_TEMP.md
