name: Create Release

on: 
  workflow_dispatch

jobs:
  lintAndTest:
    uses: ./.github/workflows/lintAndTest.yml
    
  createRelease: 
    runs-on: ubuntu-latest
    needs: lintAndTest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create release branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'releases/${{ github.run_number }}'
          sha: ${{ github.sha }}
